# .gitlab-ci.yml file blabla

image: node:latest
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/

stages:
  - validate
  - test
  - build
  - release
  - deploy

# Anchor pour la configuration commune
.default-job: &default-job
rules:
  - if: '$CI_COMMIT_BRANCH == "main"	
      && $CI_COMMIT_TAG == null	
      && $CI_COMMIT_TITLE !~ /^chore: release/'

install:
  stage: .pre
  <<: *default-job	
  script:
    # define cache dir & use it npm!
    - npm ci --cache .npm --prefer-offline

lint:	
  stage: validate	
  <<: *default-job	
  script:
    - npm run lint

only-canary:
  stage: validate
  <<: *default-job
  script:
    - echo "Hello Only Canary !"

unit-test:
  stage: test
  <<: *default-job	
  script:
    - npm test

e2e-test:
  stage: test
  needs: 
    - integration-test
  <<: *default-job
  script:
    - echo "Hello E2E !"

integration-test:
  stage: test
  needs: 
    - unit-test
  <<: *default-job 
  script:
    - echo "Hello Integration !"

release:	
  stage: release	
  when: manual	
  <<: *default-job	
  before_script:	
    - git config user.email $GITLAB_USER_EMAIL	
    - git config user.name $GITLAB_USER_NAME	
    - git remote set-url origin	
      "https://gitlab-ci-token:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"	
    - git checkout $CI_COMMIT_BRANCH	
    - git pull origin $CI_COMMIT_BRANCH --rebase	
  script:	
    - npx --yes release-it --ci


