image: node:latest

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - ".npm/"

stages:
  - setup  
  - validate
  - test
  - build
  - release
  - deploy

install:
  stage: setup  
  script:
    - npm ci --cache .npm --prefer-offline
