# .gitlab-ci.yml file
image: node:latest

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/

stages:
  - validate
  - test
  - build
  - release
  - deploy

# Job d'installation des dépendances
install:
  stage: .pre  # Le stage .pre s'exécute automatiquement avant tous les autres
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

# Job de validation
validate:
  stage: validate
  script:
    - npm run lint
  dependencies:
    - install

# Job de tests
test:
  stage: test
  script:
    - npm run test
  dependencies:
    - install
  coverage: '/Lines\s*:\s*(\d+\.\d+)%/'

# Job de build
build:
  stage: build
  script:
    - npm run build
  dependencies:
    - install
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

# Job de release
release:
  stage: release
  script:
    - echo "Creating release..."
    # Ajoutez vos commandes de release ici
  dependencies:
    - build
  only:
    - main

# Job de déploiement
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Ajoutez vos commandes de déploiement ici
  dependencies:
    - build
  only:
    - main